In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from keras.datasets import california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error

(X_train_full, y_train_full), (X_test, y_test) = california_housing.load_data(version="large", test_split=0.2, seed=42)

print(X_train_full.shape)
print(y_train_full.shape)
print(X_test.shape)
print(y_test.shape)

(16512, 8)
(16512,)
(4128, 8)
(4128,)


In [ ]:
X_train_full

array([[-119.01  ,   36.06  ,   25.    , ..., 1392.    ,  359.    ,
           1.6812],
       [-119.46  ,   35.14  ,   30.    , ..., 1565.    ,  584.    ,
           2.5313],
       [-122.44  ,   37.8   ,   52.    , ..., 1310.    ,  963.    ,
           3.4801],
       ...,
       [-120.71  ,   38.34  ,   16.    , ...,  559.    ,  213.    ,
           4.4531],
       [-117.13  ,   32.91  ,   16.    , ..., 1619.    ,  584.    ,
           4.    ],
       [-117.93  ,   33.71  ,   10.    , ..., 1581.    ,  633.    ,
           4.1366]], dtype=float32)

In [ ]:
y_train_full

array([ 47700.,  45800., 500001., ..., 144300., 154700., 158800.],
      dtype=float32)

In [ ]:
X_train, X_valid, y_train, y_valid = train_test_split(X_train_full, y_train_full, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_valid_scaled = scaler.transform(X_valid)
X_test_scaled = scaler.transform(X_test)

print(X_train_scaled.shape)
print(X_valid_scaled.shape)
print(X_test_scaled.shape)

(13209, 8)
(3303, 8)
(4128, 8)


In [ ]:
X_train_scaled

array([[-1.3428204 ,  1.1067803 , -1.8047258 , ..., -0.9856741 ,
        -1.0625787 ,  0.71047664],
       [-1.2779114 ,  0.9663894 , -0.6124807 , ...,  0.67205936,
         1.3191351 , -0.65481234],
       [ 0.82406217, -0.9476102 , -0.8509297 , ..., -0.8894823 ,
        -0.54527146,  0.76256454],
       ...,
       [-0.8884727 ,  1.3922426 , -0.13558264, ...,  0.12097983,
         0.6967909 , -0.5779382 ],
       [-0.9683595 ,  0.6481694 , -0.7714467 , ..., -0.24490817,
        -0.34307528,  0.07447006],
       [-0.45909047,  0.76984096, -1.4073107 , ...,  0.26391888,
        -0.3220679 , -1.0104142 ]], dtype=float32)

In [ ]:
model = keras.models.Sequential([
    keras.layers.Dense(30, activation="relu", input_shape=X_train_scaled.shape[1:]),
    keras.layers.Dense(30, activation="relu"),
    keras.layers.Dense(1)
])

model.compile(loss="mse", optimizer="adam")

history = model.fit(X_train_scaled, y_train, epochs=20, validation_data=(X_valid_scaled, y_valid))

Epoch 1/20


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 55648276480.0000 - val_loss: 55188553728.0000
Epoch 2/20
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 55076691968.0000 - val_loss: 53772525568.0000
Epoch 3/20
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 53125836800.0000 - val_loss: 50338410496.0000
Epoch 4/20
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50058018816.0000 - val_loss: 44818042880.0000
Epoch 5/20
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 43461480448.0000 - val_loss: 37947154432.0000
Epoch 6/20
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 36882911232.0000 - val_loss: 30710904832.0000
Epoch 7/20
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 29432594432.0000 - val_loss: 24012140544.0000
Epoch 8/20
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 22501724160.0000 - val_loss: 18544252928.0000
Epoch 9/20
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 18066456576.0000 - val_loss: 14727158784.0000
Epoch 10/20
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - lo

In [ ]:
mse_test = model.evaluate(X_test_scaled, y_test)
y_pred = model.predict(X_test_scaled)

mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(y_test, y_pred)

print(f"Test Set Loss (MSE): {mse_test}")
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"Mean Absolute Error (MAE): {mae}")

# Small explanation of metrics:
# MSE (Mean Squared Error): Measures the average squared difference. Penalizes larger errors heavily. Smaller is better.
# RMSE (Root Mean Squared Error): Error in the original unit of the target. Easier to interpret than MSE. Smaller is better.
# MAE (Mean Absolute Error): Measures the average absolute error. Less sensitive to outliers than MSE/RMSE. Smaller is better.

129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8234047488.0000
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step  
Test Set Loss (MSE): 8038785024.0
Mean Squared Error (MSE): 8038785024.0
Root Mean Squared Error (RMSE): 89659.27182394468
Mean Absolute Error (MAE): 64729.2265625


In [ ]:
#HDF5 format (legacy, but widely used)
model.save("my_regression_model.keras")

In [ ]:
loaded_model = keras.models.load_model("my_regression_model.keras")

sample_data = X_test_scaled[:5]
sample_predictions = loaded_model.predict(sample_data)

print(f"True Values (First 5): {y_test[:5]}")
print(f"Predicted Values (First 5): {sample_predictions.flatten()}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step
True Values (First 5): [ 58800. 165800. 139400. 107500. 107200.]
Predicted Values (First 5): [ 94167.54 120158.55 166141.75 165115.33 119445.63]


In [ ]:
sample_data

array([[-0.34425792,  0.6996464 ,  0.3413154 , -0.6350897 , -0.6768554 ,
        -0.68900806, -0.70545286, -0.9714793 ]], dtype=float32)